
use PROJECT

Create Table Table_A(
First_Name Varchar(255),
Designation Varchar(255),
salary integer,
State_Name varchar(255))

Insert into Table_A Values('Gagan','hr',352337,'Maharashtra')
Insert into Table_A Values('Gaurav','ceo',97852,'Delhi')
Insert into Table_A Values('Saurav','executive',241487,'Tamil Nadu')
Insert into Table_A Values('Abhishek','associate',123770,'Himachal')
Insert into Table_A Values('Raju','director',377874,'Uttrakhand')
Insert into Table_A Values('swati','manager',581952,'Rajasthan')
Insert into Table_A Values('chanchal','team leader',616605,'Jammu')


Create Table Table_B(
First_Name Varchar(255),
Emp_id Integer,
Company Varchar(255),
Department varchar(255))

Insert into Table_B Values('Roshni',2,'exl','MIS')
Insert into Table_B Values('Madhuri',3,'mercer','BI')
Insert into Table_B Values('Gagan',4,'kpmg','HR')
Insert into Table_B Values('Raju',5,'uhg','Admin')
Insert into Table_B Values('Chanchal',6,'gail','Transport')
Insert into Table_B Values('Ishika',7,'hindalco','Finance')
Insert into Table_B Values('Rajni',8,'genpact','Admin')

--sp_rename 'orderbreakdown.Order_ID','orderid','column'


select * into project.dbo.orderbreakdown from AmazingMart.dbo.OrderBreakdown
select * into project.dbo.listoforders from AmazingMart.dbo.ListOfOrders


sp_rename 'listoforders.OrderID','order_id','column'
---sp_rename 'listoforders','order_id','column'


drop table if exists PROJECT
select * into Project from listoforders as L
inner join orderbreakdown as O
on l.order_id = o.orderid

select * from project

alter table project 
add O_ID varchar(50)

alter table project
add dateonly int

alter table project
add monthonly int

alter table project
add yearonly int

alter table project
add date_differ int

alter table project
add delivery_status varchar(50)

alter table project
add cost int

select * from project

update Project
set O_ID = right(orderid,7)

update Project
set cost= sales-profit

update Project
set dateonly = day(Order_Date)

update Project
set monthonly = month(Order_Date)

update Project
set yearonly = year(Order_Date)


sp_help project
ALTER TABLE project
DROP COLUMN monthonly;



update Project
set date_differ = datediff(day,Order_Date,Ship_Date)

update project
set delivery_status= case when date_differ < 7 then 'On time'
 when date_differ =0 then 'same day'
else 'Delayed'
end

select * from project

drop table if exists status_details
select delivery_status, count(delivery_status) as total_orders
into status_details from project group by delivery_status

select * from segment_profit

drop table if exists region_sales
select state, sum(sales) as total_sales
into region_sales from project group by state

drop table if exists segment_profit
select segment, sum(profit) as total_profit
into segment_profit from project group by segment

drop table if exists orders_by_customers
select customer_name, count(order_id) as total_orders 
into orders_by_customers from project group by customer_name

select * from orders_by_customers













-- Assignment (Use AmazingMart Database)
-- Find Total Sales by Customer
select coalesce(customer_name,'Total revenue') as Customer,
		sum(sales) as total_sales 
		from project group by rollup (customer_name)
 
-- State-wise Profit
select state, sum(profit) as Profit from project group by rollup (state)
-- Top 10 Customers
select top(10) customer_name, sum(sales) as Sales 
		from project group by Customer_Name 
		order by Sales desc
-- Category-wise Sales
select category, sum(sales) from project group by Category
-- Monthly Sales
select Order_Date, sum(sales) from Project group by Order_Date

----------------------------------------------------------
--practice questions from chatgpt

       --AmazingMart----
--Give me the total revenue generated by each customer.
SELECT * from Project
SELECT Customer_Name, sum(sales) as total_revenue from Project group by Customer_Name
--Who are our top 10 customers by revenue?
select top(10)customer_Name, sum(sales) as revenue from project group by customer_name order by revenue desc
--Which customers have spent more than ₹5,000?
select customer_name, sum(sales) as revenue from project group by customer_name having sum(sales) > 5000
--Give me the total number of orders placed by each customer.
select customer_name, count(order_id) as orders_count from project group by Customer_Name order by orders_count 
--Which customers have never placed an order?
select customer_name from project where Quantity=0
--Give me the total revenue generated by each city.
select city, sum(sales) as revenue from project group by City order by revenue 
--Which city generates the highest revenue?
select top(1)city, sum(sales) as revenue from project group by City order by revenue desc
--Give me the total revenue generated by each state.
select State, sum(sales) as revenue from project group by State order by revenue 
--Which state generates the highest revenue?
--Give me the total revenue generated by each product.
--Which 10 products generate the most revenue?
--Which products have never been purchased?
--Give me the total quantity sold for each product.
--Which products have sold more than 1,000 units?
--Give me the total revenue generated by each product category.
--Which category generates the highest revenue?
--Give me the average product price for each category.
--Give me the total revenue generated by each salesperson.
--Who is our highest-performing salesperson based on revenue?
--Give me the total revenue generated in each year.
--Give me the total revenue generated in each month.
--Show revenue by customer and include a final row showing total company revenue.
--Show revenue by category and include a final row showing total company revenue.
--Give me a report showing each customer, their location, number of orders, and total revenue.
--Management wants a complete sales-performance report showing our best 
   customers, products, categories, locations, and salespeople based on revenue..


   ------------Northwind
--Give me the total revenue generated by each customer.
--Who are our top 10 customers by revenue?
--Which customers have generated more than $10,000 in revenue?
--Give me the total number of orders placed by each customer.
--Which customers have never placed an order?
--Give me the total revenue generated by each country.
--Which country is generating the highest revenue?
--Give me the total revenue generated by each product category.
--Which product category is performing the best in terms of revenue?
----Give me the total quantity sold for every product.
--Which 10 products have generated the most revenue?
--Which products have never been sold?
--Give me the average product price for each category.
--Which products currently have less than 10 units in stock?
--Give me the total revenue generated by each employee.
--Who is our highest-performing employee based on total revenue?
--How many orders has each employee handled?
--Give me the total freight cost for each country.
--Which customers have placed more than 5 orders?
--Give me the total revenue generated in each year.
--Give me the total revenue generated in each month.
--Show revenue by customer and include a final row showing total company revenue.
--Show revenue by product category and include a final row showing total company revenue.
--Give me a report showing each customer, their country, number of orders, and total revenue.
--Management wants to identify our strongest customers, products, categories, and employees. Prepare a report that shows the revenue generated by each of these four areas.

